### PR TITLE
Version 4.5.2

### PR DESCRIPTION
**Pull request by EpiCanard**
Changes :
- Set api-version to 1.13 to support new materials
- Update of vault nexus that didn't work anymore
- Add versionning of materials inside sources to have directly good materials inside config
- Remove of title variable for inventory duplication
  - Note : In 1.14 title is not part of the Inventory anymore but is inside InventoryView. Since you use only title for duplication of inventory, themselves only used for temporary manipulation, I thought it was not useful to keep it.
- Add all the translation of French. Made by @BlackDiamond

I tried every version from 1.9 to 1.14 with all type of signs and it works well.
So it now support new minecraft 1.14 signs.

### CODE REVIEW

**Comment by czymstef** [comment]
thanks for the PR 👍

**Comment by DakirDev** [comment]
Hi, is there any way to download ServerSigns.jar 4.5.2?

**Comment by czymstef** [comment]
@Dakir22 you can download the freshly build version here: https://ci.serversigns.de/job/ServerSigns/

**Comment by DakirDev** [comment]
Thank you both very much!

**Pull request merged**
